version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    # In production, no need to expose 5000 externally
    env_file:
      - MONGO_URI=${MONGO_URI}  # Jenkins will inject
      - FLASK_ENV=${FLASK_ENV}
      #- ./backend/.env  # contains MONGO_URI and other secrets
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "80:80"  # public access
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

